### PR TITLE
Add Install and Check Scripts for Tool Setup

### PR DESCRIPTION
**Pull request by kpulsr**
This pull request adds two new scripts, `Install_tools.sh` and `checkTools.sh`, to the repository. These scripts aim to streamline the setup and verification process of necessary tools for the project.

### Changes:
1. Install_tools.sh: A comprehensive script to install prerequisite tools, Go, and several Go-based and Python-based tools. It also updates the shell configuration to include the newly installed tools in the PATH.
2. checkTools.sh: A script to check the existence and proper installation of the required tools.

### Purpose:
- Simplify the installing process.
- Ensure all necessary tools are correctly installed .
- Provide an easy way to verify the installation of the tools.

### CODE REVIEW

**Comment by h0tak88r** [comment]
Hi @BigBr41n 
I am really sorry i didn't notice your pull request 
Why you closed this ?

**Comment by kpulsr** [comment]
I just reviewed the tool again and i saw that file : setup.sh 
I was like ayy yoo where did this file come from i didn't notice that you already have an installation file at all

**Comment by h0tak88r** [comment]
No worries at all! It's great to meet you my friend. 
Thank you for taking the time to review and contribute

**Comment by kpulsr** [comment]
nice too meet you brother, btw great job in bug bounty **_keep up_**

**Pull request closed without merging**
